# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a391d92c1f2ce3ae5f0294da3b1255b3bb3d741c09a2e766b911e0988045bbc140a866f84ea1c1a166afebee446009593ee7b580c0800100907cb635887e7e9

test:
  secret_key_base: 789030eb87e1c3a00eb62089168b94cdbc6e01c0f1acb8c285a35d2b28343433c306b20de13e26c1e3e7049c8acb590b3229665ca2dc5771632a95c9ae88fe93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
